[build]
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
preDeployCommand = "npx prisma db push --accept-data-loss --skip-generate && npx tsx prisma/seed.ts"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
